function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 01-Dec-2015 21:03:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1);

